salesforcecli/plugin-apex

messages/execute.md, messages/get.md, messages/list.md, messages/report.md, messages/run.md, messages/tail.md, package.json, src/commands/apex/execute.ts, src/commands/apex/log/get.ts, src/commands/apex/log/list.ts, src/commands/apex/log/tail.ts, src/commands/apex/test/report.ts, src/commands/apex/test/run.ts, test/commands/apex/test/report.test.ts, test/commands/apex/test/run.test.ts
Standardizes messages *.md files, sf-izes content, add descriptions to examples, use long flag names
@W-12460654@
=> fix: clean up messages after sf-ication

messages/execute.json, src/commands/force/apex/execute.ts, test/commands/force/apex/execute.test.ts
BREAKING CHANGE: force:apex:execute now returns an error exit code (1) when the compilation or execution of the Anonymous Apex failed.
Changes the behaviour to return an error exit code (1) when the compilation or execution of the Anonymous Apex failed.
Fixes #6 and https://github.com/forcedotcom/cli/issues/77
=> fix: exit with error code when anyonmous apex failed to compile or run

messages/runtest.md, src/commands/apex/get/test.ts, src/commands/apex/run/test.ts, test/commands/apex/run/test.test.ts, yarn.lock
* Defaults result-format to "human" for both run:test and get:test
* Makes `--code-coverage` flag depend on `--result-format` flag for run:test (moves validation out of code and into parse)
These changes restore the production of coverage files when get:test specifies `--code-coverage` and `--output-dir`
@W-12679981@
=> fix: default result format human + coverage depends on result format

messages/run.md
Corrects `apex run` examples to use `--file` instead of `--apex-code-file` which is invalid
Fixes: https://github.com/forcedotcom/cli/issues/1999
[@W-12696529@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12696529)
=> Correct examples on run

src/commands/apex/get/log.ts
Removes (and ignores) the default for the `get log --number` integer. When the default is present it takes priority over the `logId` in the apex library here: https://github.com/forcedotcom/salesforcedx-apex/blob/main/src/logs/logService.ts#L57-L60
With this removed, you still get an appropriate message when you do not pass either flag:
`Error (1): To retrieve logs, specify the log ID or the number of logs.`
Not knowing how the apex library is being used, I feel it is safer to make the change here. 
https://github.com/forcedotcom/cli/issues/2006
[@W-12726884@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12726884)
=> Remove log:get number default

messages/runtest.md
updates --help to explain that by default tests run asynch, and depending on whether they finish or not you'll see results or a n ID. 
@W-9941625@
=> fix: add info about results vs. id

src/commands/apex/run/test.ts
wait min of 1
@W-13146766@
https://github.com/forcedotcom/cli/issues/2110
`apex run test` had an undocumented use of `-1` for its `--wait` flag.  The minimum is now `0`.
=> fix: min duration for --wait on apex test run

test/commands/apex/run/test.test.ts
=> test: add UTs

messages/runtest.md, src/commands/apex/run/test.ts
Now that tests run async by default, this provides instructions on how to wait for test results. Also updates help docs to reflect the change to async by default. 
I originally used some `oclif` flag relationships to enforce this suggestion, but a lot of these flags are tightly coupled and it caused other issues. I think this quick fix is sufficient for now.
Another semi-related change: For some reason, if you passed `--synchronous` and `--json` it would immediately return with the `testRunId`. That made no sense to me, so I changed it. Let me know if you can think of a reason that this was the case.
QA Suggestions
- Run with `sf apex test run`
- Confirm `get` command is logged as well as sync suggestion
- Run with `sf apex test run --json`
- Confirm the `testRunId` exist in json
- …
=> Provide sync instructions

src/commands/apex/run/test.ts, test/commands/apex/run/test.nut.ts
the apex library writes a file when async test runs occur.  We left that out when we re-did their commands.
https://github.com/forcedotcom/cli/issues/2321
@W-13804720@
=> fix: call testService method to store testRunId

command-snapshot.json, src/commands/apex/tail/log.ts
removes the little-used, non-working --json flag from `tail log`
This command couldn't return valid json because the only way to exit it was Ctrl-C.  `--json` flag was almost never used, and didn't do anything, so we're making that official.  
You can get logs in json format using `apex list log` or `apex get log`
@W-14478850@
see thread https://salesforce-internal.slack.com/archives/C4LRHH0AD/p1699563812949449
=> feat!: remove --json from log tail

package.json, yarn.lock
Uses latest version of apex-node to prevent a TypeError when a header is missing.
@W-14750755@
=> fix: bump to latest apex lib

package.json, src/commands/apex/run/test.ts, yarn.lock
What does this PR do?
will timeout apex tests based on timeout value
What issues does this PR fix or reference?
@W-14364504@
requires: https://github.com/forcedotcom/salesforcedx-apex/pull/364
Functionality Before
tests would never timeout
Functionality After
tests timeout
=> fix: allow timeouts with --wait

package.json, yarn.lock
Pulls in fixes in the @salesforce/apex-node dependency for:
1. All Apex classes/triggers in the ApexCodeCoverageAggregate table are displayed when the "Show Only Aggregated Code Coverage" setting is checked
2. Add heap monitoring
@W-15783639@, @W-15760648@
=> chore: bump @salesforce/apex-node to v6.1.2

messages/runtest.md, package.json, src/commands/apex/get/test.ts, src/commands/apex/run/test.ts, src/reporters/testReporter.ts, test/commands/apex/get/log.test.ts, test/commands/apex/get/test.test.ts, test/commands/apex/list/log.test.ts, test/commands/apex/run.test.ts, test/commands/apex/run/test.test.ts, test/commands/apex/tail/log.test.ts, yarn.lock
use new apex lib (sfdx-core8)
UT were loading oclif/core Config, which takes a really long time.  
But removing that and switching to the static run method forced some changes in the ux stubs.
also had to add the non-ESM versions of wrap-ansi and string-width (I think because apex-node isn't ESM something is still needing them). 
[skip-validate-pr]
=> fix(deps): bump apex library

command-snapshot.json, messages/gettest.md, package.json, src/commands/apex/get/test.ts, yarn.lock
Add "--detailed-coverage" flag to "sf apex get test"
@W-16744604@
=> Code coverage

messages/runtest.md
adds note that users need the View All Data perm to run the "apex run test" command.
@W-17219678@
=> fix: add VAD perm requirement to "apex run test"

package.json, src/commands/apex/run/test.ts, yarn.lock
improves error message when no tests in the org from 
`Error (1): Always provide a classes, suites, tests, or testLevel property.`
to
```bash
Error (INVALID_INPUT): There are no apex tests to run in the org
Try this:
Ensure Apex Tests exist in the org
```
@W-17866064@
https://github.com/forcedotcom/cli/issues/3217
=> fix: improve no tests in org error message, suggest actions W-17866064

src/commands/apex/run/test.ts, test/commands/apex/run/test.test.ts
- Adds error handling to synchronous test runs.
- Tidies up formatting of replacement error message.
- Escapes when command meets valid condition of server-side error message.
https://github.com/forcedotcom/cli/issues/3217
https://github.com/forcedotcom/salesforcedx-apex/issues/306#issuecomment-1306091716
https://github.com/salesforcecli/plugin-apex/pull/706
=> fix: handle error for sync test runs & check for valid error first

test/commands/logic/get/test.nut.ts, test/commands/logic/run/test.nut.ts, test/commands/logic/testHelper.ts, test/nuts/unifiedFrameworkProject/config/project-scratch-def.json, test/nuts/unifiedFrameworkProject/force-app/main/default/flows/Populate_opp_description.flow-meta.xml, test/nuts/unifiedFrameworkProject/force-app/main/default/flowtests/test_opportunity_updates.flowtest-meta.xml, test/nuts/unifiedFrameworkProject/sfdx-project.json
Adds NUTs for `logic get test` and `logic run test` commands.
[@W-19625073@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002LdpjuYAB/view)
=> W-19625073: add NUTs for logic commands
